spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: alex
    password: alex
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: postgresql

token:
  name: ?api_token=XSVRg6P1q0rm1hDE

data:
  name: /202111171200

#    url: jdbc:postgresql://postgresqldb:5432/test
